### ISSUE TITLE
这个DEMO真的能够愉快的跑起来吗？

### ISSUE THREAD

**Issue by uncle5** [Rekoe/Rk_Cms#3]
整个项目down下来，Eclipse加载完毕，无错误提示，jetty跑起来，遇到各种问题：
1.提示 shiro.ini 为空，将shiro.ini复制到/WEB-INF下，OK
2.提示dao无法初始化，因为type=null，将/ioc/*.js复制到com.rekoe.mvc.view包下，OK
3.提示init_system_h2.sql无法找到文件，将init_system_h2.sql复制到com.rekoe包下，OK
至此，启动正常
4.访问/admin/login，
2014-08-14 16:33:28.805:WARN::/admin/login
java.lang.IllegalStateException: Committed
	at org.mortbay.jetty.Response.resetBuffer(Response.java:1023)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:211)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at org.nutz.mvc.view.ForwardView.render(ForwardView.java:70)
	at org.nutz.mvc.view.ViewWrapper.render(ViewWrapper.java:26)
	at org.nutz.mvc.impl.processor.ViewProcessor.process(ViewProcessor.java:40)
	at org.nutz.mvc.impl.processor.FailProcessor.process(FailProcessor.java:30)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:45)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:64)
	at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)

还能愉快的跑起来吗。

**Comment by wendal** [comment]
可以的
