### ISSUE TITLE
验证码无法显示

### ISSUE THREAD

**Issue by DuLerWeil** [Rekoe/Rk_Cms#9]
"C:\Program Files\Java\jdk1.7.0_72\bin\java" "-Dmaven.home=C:\Program Files\JetBrains\IntelliJ IDEA 14.1\plugins\maven\lib\maven3" "-Dclassworlds.conf=C:\Program Files\JetBrains\IntelliJ IDEA 14.1\plugins\maven\lib\maven3\bin\m2.conf" -Didea.launcher.port=7539 "-Didea.launcher.bin.path=C:\Program Files\JetBrains\IntelliJ IDEA 14.1\bin" -Dfile.encoding=GBK -classpath "C:\Program Files\JetBrains\IntelliJ IDEA 14.1\plugins\maven\lib\maven3\boot\plexus-classworlds-2.4.jar;C:\Program Files\JetBrains\IntelliJ IDEA 14.1\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.2 org.apache.tomcat.maven:tomcat6-maven-plugin:2.0-beta-1:run
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.rekoe:rk_cms:war:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 291, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rk_cms 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> tomcat6-maven-plugin:2.0-beta-1:run (default-cli) @ rk_cms >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rk_cms ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 18 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ rk_cms ---
[INFO] Compiling 1 source file to D:\Workspace\Intellij\oss\Rk_Cms\src\main\webapp\WEB-INF\classes
[INFO] 
[INFO] <<< tomcat6-maven-plugin:2.0-beta-1:run (default-cli) @ rk_cms <<<
[INFO] 
[INFO] --- tomcat6-maven-plugin:2.0-beta-1:run (default-cli) @ rk_cms ---
[INFO] Running war on http://localhost:8080/rk_cms
[INFO] Using existing Tomcat server configuration at D:\Workspace\Intellij\oss\Rk_Cms\target\tomcat
四月 26, 2015 5:51:08 下午 org.apache.catalina.startup.Embedded start
信息: Starting tomcat server
四月 26, 2015 5:51:08 下午 org.apache.catalina.core.StandardEngine start
信息: Starting Servlet Engine: Apache Tomcat/6.0.35
2015-04-26 17:51:08,799 [INFO][org.apache.shiro.web.env.EnvironmentLoader] - Starting Shiro environment initialization.
四月 26, 2015 5:51:08 下午 org.apache.catalina.core.ApplicationContext log
信息: Initializing Shiro environment
2015-04-26 17:51:08,951 [INFO][org.apache.shiro.config.IniSecurityManagerFactory] - Realms have been explicitly set on the SecurityManager instance - auto-setting of realms will not occur.
2015-04-26 17:51:08,952 [INFO][org.apache.shiro.web.env.EnvironmentLoader] - Shiro environment initialized in 151 ms.
ALL Nutz Log via Log4jLogAdapter
2015-04-26 17:51:08,966 [INFO][org.nutz.mvc.NutFilter] - NutFilter[nutz] starting ...
2015-04-26 17:51:09,016 [WARN][org.nutz.resource.Scans] - /WEB-INF/lib/ NOT found?!
2015-04-26 17:51:09,036 [INFO][org.nutz.mvc.impl.NutLoading] - Nutz Version : 1.b.52 
2015-04-26 17:51:09,036 [INFO][org.nutz.mvc.impl.NutLoading] - Nutz.Mvc[nutz] is initializing ...
2015-04-26 17:51:09,278 [INFO][org.nutz.ioc.loader.annotation.AnnotationIocLoader] - auto set as         refer:dataSource
2015-04-26 17:51:09,325 [INFO][org.nutz.ioc.loader.annotation.AnnotationIocLoader] - Scan complete ! Found 35 classes in 1 base-packages!
beans = ["quartzService", "articleCategoryService", "commonAct", "permissionCategoryService", "articleModule", "userService", "snakerFacets", "fileAct", "crawlerRuleService", "adminRoleAct", "acquisitionService", "adminUserAct", "fileService", "acquisitionTempService", "settingService", "loginModule", "permissionService", "socialAuthConfig", "acquisitionAct", "settingAct", "salesAct", "adminLoginAct", "roleService", "indexModule", "jPEGView", "photoModul", "permissionCategoryAct", "statisticsAct", "captchaModule", "crawlerAct", "articleCategoryAct", "oauthLoginAct", "articleService", "permissionAct", "articleAct"]
2015-04-26 17:51:09,331 [INFO][org.nutz.mvc.impl.NutLoading] - Build URL mapping by org.nutz.mvc.impl.UrlMappingImpl ...
2015-04-26 17:51:09,830 [INFO][org.nutz.mvc.impl.NutLoading] - Found 95 module methods
2015-04-26 17:51:09,835 [INFO][org.nutz.mvc.impl.NutLoading] - Setup application...
2015-04-26 17:51:10,157 [INFO][org.nutz.mvc.impl.NutLoading] - Nutz.Mvc[nutz] is up in 1120ms
四月 26, 2015 5:51:10 下午 org.apache.coyote.http11.Http11Protocol init
信息: Initializing Coyote HTTP/1.1 on http-8080
四月 26, 2015 5:51:10 下午 org.apache.coyote.http11.Http11Protocol start
信息: Starting Coyote HTTP/1.1 on http-8080
2015-04-26 17:51:15,700 [WARN][org.nutz.mvc.impl.processor.FailProcessor] - Error@/captcha :
com.octo.captcha.CaptchaException: n must be positive
	at com.octo.captcha.image.gimpy.GimpyFactory.getImageCaptcha(GimpyFactory.java:79)
	at com.rekoe.mvc.view.AbstractCaptchaEngine.getNextImageCaptcha(AbstractCaptchaEngine.java:67)
	at com.octo.captcha.engine.image.ImageCaptchaEngine.getNextCaptcha(ImageCaptchaEngine.java:52)
	at com.octo.captcha.service.AbstractCaptchaService.generateAndStoreCaptcha(AbstractCaptchaService.java:148)
	at com.octo.captcha.service.AbstractManageableCaptchaService.generateCountTimeStampAndStoreCaptcha(AbstractManageableCaptchaService.java:340)
	at com.octo.captcha.service.AbstractManageableCaptchaService.generateAndStoreCaptcha(AbstractManageableCaptchaService.java:329)
	at com.octo.captcha.service.AbstractCaptchaService.getChallengeForID(AbstractCaptchaService.java:64)
	at com.rekoe.module.CaptchaModule.captcha(CaptchaModule.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.nutz.mvc.impl.processor.MethodInvokeProcessor.process(MethodInvokeProcessor.java:23)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.AdaptorProcessor.process(AdaptorProcessor.java:33)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ActionFiltersProcessor.process(ActionFiltersProcessor.java:40)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.ModuleProcessor.process(ModuleProcessor.java:113)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.EncodingProcessor.process(EncodingProcessor.java:27)
	at org.nutz.mvc.impl.processor.AbstractProcessor.doNext(AbstractProcessor.java:44)
	at org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor.process(UpdateRequestAttributesProcessor.java:15)
	at org.nutz.mvc.impl.NutActionChain.doChain(NutActionChain.java:40)
	at org.nutz.mvc.impl.ActionInvoker.invoke(ActionInvoker.java:64)
	at org.nutz.mvc.ActionHandler.handle(ActionHandler.java:31)
	at org.nutz.mvc.NutFilter.doFilter(NutFilter.java:182)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:602)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: n must be positive
	at java.util.Random.nextInt(Random.java:300)
	at com.rekoe.cms.image.FileReaderRandomBackgroundGenerator.getBackground(FileReaderRandomBackgroundGenerator.java:149)
	at com.octo.captcha.component.image.wordtoimage.ComposedWordToImage.getBackround(ComposedWordToImage.java:116)
	at com.octo.captcha.component.image.wordtoimage.AbstractWordToImage.getImage(AbstractWordToImage.java:50)
	at com.octo.captcha.image.gimpy.GimpyFactory.getImageCaptcha(GimpyFactory.java:77)
	... 47 more

**Comment by DuLerWeil** [comment]
依然是maven资源文件的问题，src/main/java里只能放java源码文件，资源文件都得放到resources。
否则编译及打包的时候都会被过滤。
你们用的eclipse不报错，因为它默认开启自动编译，src/main/java里的资源文件也处理了。
但这是eclipse的行为，而不是maven的。

**Comment by Rekoe** [comment]
用maven打的war包和jar包都没有发现你说的这个问题啊
@DuLerWeil

**Comment by CangWolf** [comment]
确实是资源的问题，我也是醉了，终于好了
